DROP DATABASE IF EXISTS ircloki;
CREATE DATABASE ircloki;
USE ircloki;
CREATE TABLE loki (
  id INT PRIMARY KEY AUTO_INCREMENT,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  nick VARCHAR(20) NOT NULL,
  message TEXT NOT NULL
);